const DATA_URL = "https://gist.githubusercontent.com/enjalot/9244085/raw/freq.tsv";
const fallback = [
  ["的","de","possessive particle · of"],["一","yī","one · single"],["是","shì","to be · yes"],["不","bù","not · no"],["了","le","completed-action or change particle"],["在","zài","at · located in · exist"],["人","rén","person · people"],["有","yǒu","to have · there is"],["我","wǒ","I · me"],["他","tā","he · him"]
].map(([character,pinyin,meaning],i)=>({rank:i+1,character,pinyin,meaning}));
const partnerMap={"的":["我的","好的","目的","真的"],"一":["一个","一起","一样","第一"],"是":["不是","但是","还是","就是"],"不":["不是","不能","不要","不错"],"了":["好了","来了","了解","除了"],"在":["现在","正在","存在","在家"],"人":["人民","个人","别人","家人"],"有":["没有","所有","只有","还有"],"我":["我们","我的","自我","忘我"],"他":["他们","其他","他的","他人"]};
const partnerDetails={
  "我的":["wǒ de","my · mine"],"好的":["hǎo de","okay · good"],"目的":["mù dì","purpose · objective"],"真的":["zhēn de","really · genuine"],
  "一个":["yí ge","one · a single"],"一起":["yì qǐ","together"],"一样":["yí yàng","the same · alike"],"第一":["dì yī","first"],
  "不是":["bú shì","is not · no"],"但是":["dàn shì","but · however"],"还是":["hái shì","or · still"],"就是":["jiù shì","exactly · simply is"],
  "不能":["bù néng","cannot"],"不要":["bú yào","do not · do not want"],"不错":["bú cuò","not bad · correct"],
  "好了":["hǎo le","all right · finished"],"来了":["lái le","has arrived"],"了解":["liǎo jiě","to understand"],"除了":["chú le","except for · besides"],
  "现在":["xiàn zài","now · at present"],"正在":["zhèng zài","in the process of"],"存在":["cún zài","to exist"],"在家":["zài jiā","at home"],
  "人民":["rén mín","the people"],"个人":["gè rén","individual · personal"],"别人":["bié ren","other people"],"家人":["jiā rén","family member"],
  "没有":["méi yǒu","not have · there is not"],"所有":["suǒ yǒu","all · to possess"],"只有":["zhǐ yǒu","only have · only if"],"还有":["hái yǒu","also · in addition"],
  "我们":["wǒ men","we · us"],"自我":["zì wǒ","self"],"忘我":["wàng wǒ","selfless · absorbed"],
  "他们":["tā men","they · them"],"其他":["qí tā","other · the rest"],"他的":["tā de","his"],"他人":["tā rén","other people"]
};
let entries=fallback,current=0,strokes=[],drawing=false,guideOn=true;
const $=id=>document.getElementById(id),canvas=$("trace-canvas"),ctx=canvas.getContext("2d");
function tonePinyin(value){const map={a:["ā","á","ǎ","à"],e:["ē","é","ě","è"],i:["ī","í","ǐ","ì"],o:["ō","ó","ǒ","ò"],u:["ū","ú","ǔ","ù"],v:["ǖ","ǘ","ǚ","ǜ"]};return value.replace(/([a-züv]+)([1-4])/gi,(_,s,t)=>{const lower=s.toLowerCase().replace("ü","v");let pos=lower.indexOf("a");if(pos<0)pos=lower.indexOf("e");if(pos<0&&lower.includes("ou"))pos=lower.indexOf("o");if(pos<0){for(let i=lower.length-1;i>=0;i--)if("aeiouv".includes(lower[i])){pos=i;break}}return pos<0?s:s.slice(0,pos)+map[lower[pos]][+t-1]+s.slice(pos+1)}).replaceAll("v","ü")}
function parseData(text){return text.split(/\r?\n/).slice(1).map(line=>{const m=line.trim().match(/^(\d+)\s+(\S)\s+\d+\s+[\d.]+\s+(\S+)\s+(.+)$/);return m?{rank:+m[1],character:m[2],pinyin:tonePinyin(m[3].split("/")[0]),meaning:m[4].replaceAll("/"," · ")}:null}).filter(Boolean).slice(0,1000)}
async function loadData(){try{const response=await fetch(DATA_URL);if(!response.ok)throw Error();const parsed=parseData(await response.text());if(parsed.length<1000)throw Error();entries=parsed;$("data-status").textContent="top 1,000 loaded";show(0)}catch{$("data-status").textContent="offline starter set"}}
function resize(){const rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);renderCanvas()}
function renderCanvas(){const {width,height}=canvas.getBoundingClientRect();ctx.clearRect(0,0,width,height);if(guideOn){ctx.save();ctx.globalAlpha=.13;ctx.fillStyle="#9d3c08";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`900 ${width*.72}px 'Noto Sans SC'`;ctx.fillText(entries[current].character,width/2,height/2+width*.025);ctx.restore()}ctx.strokeStyle="#2a1207";ctx.lineWidth=Math.max(7,width*.018);ctx.lineCap="round";ctx.lineJoin="round";strokes.forEach(points=>{if(points.length<2)return;ctx.beginPath();ctx.moveTo(points[0].x*width,points[0].y*height);points.slice(1).forEach(p=>ctx.lineTo(p.x*width,p.y*height));ctx.stroke()})}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
canvas.addEventListener("pointerdown",e=>{drawing=true;canvas.setPointerCapture(e.pointerId);strokes.push([point(e)])});canvas.addEventListener("pointermove",e=>{if(!drawing)return;strokes.at(-1).push(point(e));renderCanvas()});canvas.addEventListener("pointerup",()=>drawing=false);canvas.addEventListener("pointercancel",()=>drawing=false);
function show(index){current=(index+entries.length)%entries.length;const item=entries[current];$("rank").value=item.rank;$("rank-label").textContent=`#${item.rank}`;$("character").textContent=item.character;$("pinyin").textContent=item.pinyin;$("meaning").textContent=item.meaning;const words=partnerMap[item.character]||[`${item.character}…`,`…${item.character}`];$("partners").replaceChildren(...words.map(word=>{const chip=document.createElement("span");const detail=partnerDetails[word]||[item.pinyin,`Example pattern containing ${item.character} · definition not yet available`];chip.className="partner";chip.tabIndex=0;chip.textContent=word;chip.dataset.tooltip=`${detail[0]} — ${detail[1]}`;chip.setAttribute("aria-label",`${word}: ${detail[0]}, ${detail[1]}`);return chip}));strokes=[];renderCanvas()}
$("go").onclick=()=>show(Math.max(1,Math.min(entries.length,+$("rank").value||1))-1);$("rank").addEventListener("keydown",e=>{if(e.key==="Enter")$("go").click()});$("random").onclick=()=>show(Math.floor(Math.random()*entries.length));$("previous").onclick=()=>show(current-1);$("next").onclick=()=>show(current+1);$("clear").onclick=()=>{strokes=[];renderCanvas()};$("undo").onclick=()=>{strokes.pop();renderCanvas()};$("guide").onclick=()=>{guideOn=!guideOn;$("guide").textContent=`Guide ${guideOn?"on":"off"}`;$("guide").setAttribute("aria-pressed",guideOn);renderCanvas()};
new ResizeObserver(resize).observe(canvas);loadData();
