const canvas=document.querySelector('#flag'),ctx=canvas.getContext('2d');
const ratio=document.querySelector('#ratio'),pattern=document.querySelector('#pattern');
const colorsEl=document.querySelector('#colors'),layersEl=document.querySelector('#layers');
const palettes={solid:['#f46b16'],h2:['#ffffff','#f46b16'],v2:['#f46b16','#ffffff'],h3:['#f46b16','#ffffff','#1f2c45'],v3:['#1f2c45','#ffffff','#f46b16'],hstripe:['#f4e7d3','#f46b16'],vstripe:['#f4e7d3','#f46b16'],diagonal:['#f46b16','#f4e7d3']};
let colors=[...palettes.solid],layers=[];

function setSize(){const [w,h]=ratio.value.split(':').map(Number);canvas.width=900;canvas.height=Math.round(900*h/w);document.querySelector('#dimensions').textContent=`${canvas.width} × ${canvas.height}`;draw()}
function colorControls(){colorsEl.innerHTML='';colors.forEach((color,i)=>{const row=document.createElement('label');row.className='color-row';row.innerHTML=`<span>Color ${i+1}</span><input type="color" value="${color}" aria-label="Color ${i+1}">`;row.querySelector('input').addEventListener('input',e=>{colors[i]=e.target.value;draw()});colorsEl.append(row)})}
function draw(){const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const fill=(c,x,y,a,b)=>{ctx.fillStyle=c;ctx.fillRect(x,y,a,b)};switch(pattern.value){case'h2':colors.forEach((c,i)=>fill(c,0,i*h/2,w,h/2));break;case'v2':colors.forEach((c,i)=>fill(c,i*w/2,0,w/2,h));break;case'h3':colors.forEach((c,i)=>fill(c,0,i*h/3,w,h/3));break;case'v3':colors.forEach((c,i)=>fill(c,i*w/3,0,w/3,h));break;case'hstripe':fill(colors[0],0,0,w,h);fill(colors[1],0,h/3,w,h/3);break;case'vstripe':fill(colors[0],0,0,w,h);fill(colors[1],w/3,0,w/3,h);break;case'diagonal':fill(colors[0],0,0,w,h);ctx.fillStyle=colors[1];ctx.beginPath();ctx.moveTo(w,0);ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.closePath();ctx.fill();break;default:fill(colors[0],0,0,w,h)}layers.slice().reverse().forEach(layer=>{const size=Math.min(w,h)*layer.scale/100,x=(w-size)*layer.x/100,y=(h-size)*layer.y/100;ctx.drawImage(layer.img,x,y,size,size)})}
function renderLayers(){layersEl.innerHTML='';if(!layers.length){layersEl.innerHTML='<p class="empty">No image layers yet.</p>';return}layers.forEach((layer,i)=>{const el=document.createElement('div');el.className='layer';el.innerHTML=`<div class="layer-title"><b>${layer.name}</b><span><button class="icon-btn up" title="Move forward">↑</button><button class="icon-btn down" title="Move back">↓</button><button class="icon-btn remove" title="Remove">×</button></span></div><div class="layer-tools"><label>Size<input class="scale" type="range" min="10" max="130" value="${layer.scale}"></label><label>Horizontal<input class="x" type="range" min="0" max="100" value="${layer.x}"></label><label>Vertical<input class="y" type="range" min="0" max="100" value="${layer.y}"></label></div>`;['scale','x','y'].forEach(key=>el.querySelector('.'+key).addEventListener('input',e=>{layer[key]=+e.target.value;draw()}));el.querySelector('.remove').onclick=()=>{layers.splice(i,1);renderLayers();draw()};el.querySelector('.up').onclick=()=>{if(i>0)[layers[i-1],layers[i]]=[layers[i],layers[i-1]];renderLayers();draw()};el.querySelector('.down').onclick=()=>{if(i<layers.length-1)[layers[i+1],layers[i]]=[layers[i],layers[i+1]];renderLayers();draw()};layersEl.append(el)})}
pattern.addEventListener('change',()=>{colors=[...palettes[pattern.value]];colorControls();draw()});ratio.addEventListener('change',setSize);
document.querySelector('#upload').addEventListener('change',e=>{[...e.target.files].forEach(file=>{const img=new Image();img.onload=()=>{layers.unshift({name:file.name,img,scale:45,x:50,y:50});renderLayers();draw();URL.revokeObjectURL(img.src)};img.src=URL.createObjectURL(file)});e.target.value='' });
document.querySelector('#export').onclick=()=>{const a=document.createElement('a');a.download='my-flag.png';a.href=canvas.toDataURL('image/png');a.click()};
colorControls();setSize();
