const $=s=>document.querySelector(s);const source=$('#source'),candidates=$('#candidates'),savedBox=$('#saved');let view='similes',analysis={similes:[],rare:[]};let saved=JSON.parse(localStorage.getItem('ot2-idioms')||'[]');
const stop=new Set('the a an and or but if then than to of in on at by for from with into through during before after above below up down out off over under again further once here there when where why how all any both each few more most other some such no nor not only own same so too very can will just don should now i me my myself we our ours ourselves you your yours yourself he him his she her hers it its they them their what which who this that these those am is are was were be been being have has had do does did would should could ought im youre hes shes its were theyre ive youve weve theyve isnt arent wasnt werent'.split(' '));
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){localStorage.setItem('ot2-idioms',JSON.stringify(saved));renderSaved()}
function analyze(){let text=source.value.trim();if(!text)return;let sentences=text.match(/[^.!?\n]+(?:[.!?]+|$)/g)||[];let similes=sentences.filter(s=>/\b(like|as)\b/i.test(s)).map(s=>({text:s.trim(),kind:'Simile candidate'}));let words=(text.toLowerCase().match(/[a-z][a-z'-]{2,}/g)||[]).map(w=>w.replace(/^'|'$/g,''));let counts={};words.forEach(w=>counts[w]=(counts[w]||0)+1);let rare=[...new Set(words.filter(w=>counts[w]===1&&!stop.has(w)&&!/(ing|ed|ly)$/.test(w)))].map(w=>{let context=sentences.find(s=>new RegExp(`\\b${w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i').test(s))||w;return{text:w,context:context.trim(),kind:'One-off content word'}});analysis={similes,rare};$('#simileCount').textContent=similes.length;$('#rareCount').textContent=rare.length;$('#stats').textContent=`${words.length} words · ${sentences.length} lines/sentences`;render()}
function marked(item){if(view==='similes')return esc(item.text).replace(/\b(like|as)\b/gi,'<mark class="hit">$1</mark>');return `<strong>${esc(item.text)}</strong><small>${esc(item.context)}</small>`}
function render(){let items=analysis[view];if(!items.length){candidates.className='candidates empty';candidates.textContent=view==='similes'?'No simile candidates yet.':'No one-off content words yet.';return}candidates.className='candidates';candidates.innerHTML=items.map((x,i)=>{let exists=saved.some(s=>s.text===x.text);return `<article class="candidate"><p>${marked(x)}<small>${x.kind}</small></p><button class="add ${exists?'saved-state':''}" data-i="${i}" title="Collect phrase">${exists?'✓':'+'}</button></article>`}).join('')}
function renderSaved(){let q=$('#filter').value.toLowerCase(),items=saved.filter(x=>x.text.toLowerCase().includes(q));$('#savedCount').textContent=`${saved.length} saved`;if(!items.length){savedBox.className='saved empty';savedBox.textContent=saved.length?'Nothing matches that filter.':'Collect a phrase to keep it here.';return}savedBox.className='saved';savedBox.innerHTML=items.map(x=>`<article class="saved-item"><p>${esc(x.text)}<small>${esc(x.kind)}</small></p><button class="remove" data-id="${x.id}" title="Remove">×</button></article>`).join('')}
$('#analyze').onclick=analyze;$('#clear').onclick=()=>{source.value='';analysis={similes:[],rare:[]};$('#simileCount').textContent=$('#rareCount').textContent='0';$('#stats').textContent='Waiting for text';render()};$('#sample').onclick=()=>{source.value='My love is like a red, red rose. The moon hangs as quiet as an unanswered telephone. City windows blink while a solitary bicycle waits beneath the rain.';analyze()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelector('.tab.active').classList.remove('active');b.classList.add('active');view=b.dataset.view;render()});candidates.onclick=e=>{let b=e.target.closest('.add');if(!b)return;let x=analysis[view][+b.dataset.i];if(!saved.some(s=>s.text===x.text))saved.unshift({...x,id:Date.now()});persist();render()};savedBox.onclick=e=>{let b=e.target.closest('.remove');if(b){saved=saved.filter(x=>x.id!=b.dataset.id);persist();render()}};$('#filter').oninput=renderSaved;$('#clearSaved').onclick=()=>{if(saved.length&&confirm('Empty your collected phrases?')){saved=[];persist();render()}};$('#export').onclick=()=>{if(!saved.length)return;let blob=new Blob([saved.map(x=>`${x.text}\t[${x.kind}]`).join('\n')],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='idiom-collection.txt';a.click();URL.revokeObjectURL(a.href)};renderSaved();render();
