(function registerCyrillicData() {
  const cyrillicStrokeSteps = {
    a: ["Draw the left diagonal up toward the apex.", "Draw the right diagonal down.", "Add the middle bar across."],
    be: ["Draw the top bar from left to right.", "Drop the left side straight down.", "Curve the lower bowl outward to the right."],
    ve: ["Draw the left vertical stroke from top to bottom.", "Add the upper rounded bowl.", "Add the lower rounded bowl."],
    ge: ["Draw the top bar from left to right.", "Drop the left side straight down."],
    de: ["Draw the roof line across the top.", "Bring the right side straight down.", "Finish with the wide base."],
    ie: ["Draw the left vertical stroke from top to bottom.", "Add the top bar.", "Add the middle bar.", "Add the bottom bar."],
    io: ["Draw the left vertical stroke from top to bottom.", "Add the top bar.", "Add the middle bar.", "Add the bottom bar.", "Place the two dots above."],
    zhe: ["Draw the center vertical stroke.", "Add the upper left and upper right diagonals.", "Add the lower left and lower right diagonals."],
    ze: ["Draw the upper curve.", "Bend through the middle.", "Finish with the lower curve."],
    i: ["Draw the left vertical stroke down.", "Connect with a diagonal to the lower right.", "Draw the right vertical stroke up."],
    shortI: ["Draw the left vertical stroke down.", "Connect with a diagonal to the lower right.", "Draw the right vertical stroke up.", "Add the breve above."],
    ka: ["Draw the left vertical stroke.", "Add the upper diagonal to the right.", "Add the lower diagonal to the right."],
    el: ["Draw the left slanted leg.", "Draw the right leg rising to the top."],
    em: ["Draw the left vertical stroke.", "Pull a diagonal to the center base.", "Draw the diagonal up to the top right.", "Finish with the right vertical stroke."],
    en: ["Draw the left vertical stroke.", "Add the middle bar across.", "Draw the right vertical stroke."],
    o: ["Trace the rounded loop in one continuous motion."],
    pe: ["Draw the top bar from left to right.", "Drop the left vertical stroke.", "Drop the right vertical stroke."],
    er: ["Draw the left vertical stroke.", "Add the upper rounded bowl on the right."],
    es: ["Draw the open curve from top to bottom."],
    te: ["Draw the top bar from left to right.", "Drop the center stem straight down."],
    u: ["Draw the short left diagonal toward the center.", "Draw the long right diagonal down below the baseline."],
    ef: ["Draw the center vertical stroke.", "Trace the circle around the middle."],
    kha: ["Draw the diagonal from top left to bottom right.", "Draw the diagonal from top right to bottom left."],
    tse: ["Draw the top bar from left to right.", "Drop the left vertical stroke.", "Drop the right vertical stroke.", "Add the short tail below the right side."],
    che: ["Draw the short left stroke downward.", "Sweep the top arm to the right.", "Drop the long right stroke straight down."],
    sha: ["Draw the left vertical stroke.", "Draw the middle vertical stroke.", "Draw the right vertical stroke.", "Connect them with the base line."],
    shcha: ["Draw the left vertical stroke.", "Draw the middle vertical stroke.", "Draw the right vertical stroke.", "Connect them with the base line.", "Add the short tail below the right side."],
    hardSign: ["Draw the left vertical stroke.", "Add the top bar to the right.", "Build the lower rounded bowl on the right."],
    yery: ["Draw the left vertical stroke.", "Build the rounded bowl beside it.", "Finish with the right vertical stroke."],
    softSign: ["Draw the left vertical stroke.", "Add the top arm to the right.", "Build the lower rounded bowl."],
    e: ["Draw the top arm from left to right.", "Curve around the open middle.", "Finish with the bottom arm."],
    yu: ["Draw the left vertical stroke.", "Add the short connector toward the bowl.", "Trace the round right side."],
    ya: ["Draw the left vertical stroke.", "Build the upper bowl on the right.", "Finish with the diagonal leg down to the right."]
  };

  window.ScriptLearningData.SCRIPTS.cyrillic = {
    id: "cyrillic",
    name: "Cyrillic",
    headline: "Cyrillic Script Learning Studio",
    heroTitle: "Recognize the letter, lock in the sound, trace the form.",
    heroText:
      "Work through the modern Russian Cyrillic alphabet with the same speed match, quick choice, and trace flow, plus browser pronunciation when available.",
    countLabel: "33 Russian letters",
    sampleText: "А Б В Г Д",
    unitSingular: "letter",
    unitPlural: "letters",
    glyphFont: '"Georgia", "Times New Roman", "Noto Serif", serif',
    fontLoad: "160px Georgia",
    textDirection: "ltr",
    speechLang: "ru-RU",
    voiceHints: ["russian", "irina", "olga", "alena", "milena", "pavel", "yuri"],
    speechRate: 0.84,
    matchDescription: "Match Cyrillic letters to their English sound cues and keep your streak alive.",
    traceDescription: "Trace printed Cyrillic forms, follow ordered cues, and hear the Russian letter names.",
    traceBoardNote:
      "The board shows the printed Cyrillic character directly. Use the ordered steps on the right as your stroke guide.",
    practiceNote:
      "This trainer focuses on printed Cyrillic recognition and shape memory. Use the replayed steps to build consistent letter formation before handwriting variations.",
    strokeCaption: "Replay walks the ordered Cyrillic stroke cues listed below.",
    strokeEmpty: "Replay will step through the ordered Cyrillic strokes listed below.",
    theme: {
      "bg-1": "#15281f",
      "bg-2": "#3b6a58",
      accent: "#c96a45",
      "accent-deep": "#934526",
      gold: "#eec26a",
      teal: "#2d6d5a"
    },
    strokeDemoFiles: {},
    letters: [
      { id: "a", symbol: "А", name: "A", nativeName: "а", soundLabel: "a", soundHint: 'like "a" in "father"', note: "Cyrillic А matches the Latin A in both look and sound.", speechText: "а", strokeSteps: [...cyrillicStrokeSteps.a] },
      { id: "be", symbol: "Б", name: "Be", nativeName: "б", soundLabel: "b", soundHint: 'like "b" in "book"', note: "Б uses a top bar and a rounded lower bowl for the b sound.", speechText: "бэ", strokeSteps: [...cyrillicStrokeSteps.be] },
      { id: "ve", symbol: "В", name: "Ve", nativeName: "в", soundLabel: "v", soundHint: 'like "v" in "voice"', note: "В looks like a Latin B, but it sounds like v.", speechText: "вэ", strokeSteps: [...cyrillicStrokeSteps.ve] },
      { id: "ge", symbol: "Г", name: "Ge", nativeName: "г", soundLabel: "g", soundHint: 'like "g" in "go"', note: "Г is a simple corner-shaped letter for the g sound.", speechText: "гэ", strokeSteps: [...cyrillicStrokeSteps.ge] },
      { id: "de", symbol: "Д", name: "De", nativeName: "д", soundLabel: "d", soundHint: 'like "d" in "dog"', note: "Д has a roof-like top and a wide base in its printed form.", speechText: "дэ", strokeSteps: [...cyrillicStrokeSteps.de] },
      { id: "ie", symbol: "Е", name: "Ye", nativeName: "е", soundLabel: "ye / e", soundHint: 'often sounds like "ye" at the start of a word', note: "Е looks like a Latin E, but often begins with a y glide.", speechText: "е", strokeSteps: [...cyrillicStrokeSteps.ie] },
      { id: "io", symbol: "Ё", name: "Yo", nativeName: "ё", soundLabel: "yo", soundHint: 'like "yo" in "yonder"', note: "Ё is the dotted partner of Е and always marks the yo sound.", speechText: "ё", strokeSteps: [...cyrillicStrokeSteps.io] },
      { id: "zhe", symbol: "Ж", name: "Zhe", nativeName: "ж", soundLabel: "zh", soundHint: 'like the "s" in "measure"', note: "Ж spreads out from a center stem to make the zh sound.", speechText: "жэ", strokeSteps: [...cyrillicStrokeSteps.zhe] },
      { id: "ze", symbol: "З", name: "Ze", nativeName: "з", soundLabel: "z", soundHint: 'like "z" in "zebra"', note: "З is a curved letter for the z sound.", speechText: "зэ", strokeSteps: [...cyrillicStrokeSteps.ze] },
      { id: "i", symbol: "И", name: "I", nativeName: "и", soundLabel: "i / ee", soundHint: 'like "ee" in "see"', note: "И is the straight-backed vowel for the i sound.", speechText: "и", strokeSteps: [...cyrillicStrokeSteps.i] },
      { id: "short-i", symbol: "Й", name: "Short I", nativeName: "й", soundLabel: "y", soundHint: 'like "y" in "boy"', note: "Й is И with a breve above and works like a short y sound.", speechText: "и краткое", strokeSteps: [...cyrillicStrokeSteps.shortI] },
      { id: "ka", symbol: "К", name: "Ka", nativeName: "к", soundLabel: "k", soundHint: 'like "k" in "kite"', note: "К looks like a Latin K and sounds similar too.", speechText: "ка", strokeSteps: [...cyrillicStrokeSteps.ka] },
      { id: "el", symbol: "Л", name: "El", nativeName: "л", soundLabel: "l", soundHint: 'like "l" in "lamp"', note: "Л uses two legs that meet near the top for the l sound.", speechText: "эл", strokeSteps: [...cyrillicStrokeSteps.el] },
      { id: "em", symbol: "М", name: "Em", nativeName: "м", soundLabel: "m", soundHint: 'like "m" in "moon"', note: "М matches the Latin M in both look and sound.", speechText: "эм", strokeSteps: [...cyrillicStrokeSteps.em] },
      { id: "en", symbol: "Н", name: "En", nativeName: "н", soundLabel: "n", soundHint: 'like "n" in "net"', note: "Н looks like Latin H, but it sounds like n.", speechText: "эн", strokeSteps: [...cyrillicStrokeSteps.en] },
      { id: "o", symbol: "О", name: "O", nativeName: "о", soundLabel: "o", soundHint: 'like "o" in "told"', note: "О is the round vowel letter for the o sound.", speechText: "о", strokeSteps: [...cyrillicStrokeSteps.o] },
      { id: "pe", symbol: "П", name: "Pe", nativeName: "п", soundLabel: "p", soundHint: 'like "p" in "pen"', note: "П looks a bit like a gate and sounds like p.", speechText: "пэ", strokeSteps: [...cyrillicStrokeSteps.pe] },
      { id: "er", symbol: "Р", name: "Er", nativeName: "р", soundLabel: "r", soundHint: "a rolled or tapped r", note: "Р looks like Latin P, but it sounds like r.", speechText: "эр", strokeSteps: [...cyrillicStrokeSteps.er] },
      { id: "es", symbol: "С", name: "Es", nativeName: "с", soundLabel: "s", soundHint: 'like "s" in "sun"', note: "С looks like Latin C, but it sounds like s.", speechText: "эс", strokeSteps: [...cyrillicStrokeSteps.es] },
      { id: "te", symbol: "Т", name: "Te", nativeName: "т", soundLabel: "t", soundHint: 'like "t" in "top"', note: "Т is the straight top-and-stem letter for t.", speechText: "тэ", strokeSteps: [...cyrillicStrokeSteps.te] },
      { id: "u", symbol: "У", name: "U", nativeName: "у", soundLabel: "u / oo", soundHint: 'like "oo" in "boot"', note: "У hangs below the line a little like a printed y shape.", speechText: "у", strokeSteps: [...cyrillicStrokeSteps.u] },
      { id: "ef", symbol: "Ф", name: "Ef", nativeName: "ф", soundLabel: "f", soundHint: 'like "f" in "fan"', note: "Ф combines a center stem with a circle for the f sound.", speechText: "эф", strokeSteps: [...cyrillicStrokeSteps.ef] },
      { id: "kha", symbol: "Х", name: "Kha", nativeName: "х", soundLabel: "kh / h", soundHint: 'a rougher sound, like the "ch" in "Bach"', note: "Х looks like Latin X, but it usually sounds like a rough h or kh.", speechText: "ха", strokeSteps: [...cyrillicStrokeSteps.kha] },
      { id: "tse", symbol: "Ц", name: "Tse", nativeName: "ц", soundLabel: "ts", soundHint: 'like "ts" in "cats"', note: "Ц is the ts letter with a short tail below the baseline.", speechText: "цэ", strokeSteps: [...cyrillicStrokeSteps.tse] },
      { id: "che", symbol: "Ч", name: "Che", nativeName: "ч", soundLabel: "ch", soundHint: 'like "ch" in "cheese"', note: "Ч uses a short left arm and a strong right leg for the ch sound.", speechText: "чэ", strokeSteps: [...cyrillicStrokeSteps.che] },
      { id: "sha", symbol: "Ш", name: "Sha", nativeName: "ш", soundLabel: "sh", soundHint: 'like "sh" in "ship"', note: "Ш has three vertical strokes joined along the base.", speechText: "ша", strokeSteps: [...cyrillicStrokeSteps.sha] },
      { id: "shcha", symbol: "Щ", name: "Shcha", nativeName: "щ", soundLabel: "shch", soundHint: "a longer sh sound that blends into ch", note: "Щ extends Ш with a short tail for the shch sound.", speechText: "ща", strokeSteps: [...cyrillicStrokeSteps.shcha] },
      { id: "hard-sign", symbol: "Ъ", name: "Hard Sign", nativeName: "ъ", soundLabel: "hard sign", soundHint: "a separator after a hard consonant", note: "Ъ does not carry a vowel sound of its own. It marks a hard break before the next vowel.", speechText: "твёрдый знак", strokeSteps: [...cyrillicStrokeSteps.hardSign] },
      { id: "yery", symbol: "Ы", name: "Yery", nativeName: "ы", soundLabel: "y", soundHint: "a deep vowel with the tongue pulled back", note: "Ы is a distinctive Russian vowel that has no direct English match.", speechText: "ы", strokeSteps: [...cyrillicStrokeSteps.yery] },
      { id: "soft-sign", symbol: "Ь", name: "Soft Sign", nativeName: "ь", soundLabel: "soft sign", soundHint: "softens the consonant before it", note: "Ь also lacks its own vowel sound. It softens the consonant that comes before it.", speechText: "мягкий знак", strokeSteps: [...cyrillicStrokeSteps.softSign] },
      { id: "e", symbol: "Э", name: "E", nativeName: "э", soundLabel: "e", soundHint: 'like "e" in "met", without a y glide', note: "Э is the open e vowel that does not begin with a y sound.", speechText: "э", strokeSteps: [...cyrillicStrokeSteps.e] },
      { id: "yu", symbol: "Ю", name: "Yu", nativeName: "ю", soundLabel: "yu", soundHint: 'like "you"', note: "Ю combines a short stem and a round bowl for the yu sound.", speechText: "ю", strokeSteps: [...cyrillicStrokeSteps.yu] },
      { id: "ya", symbol: "Я", name: "Ya", nativeName: "я", soundLabel: "ya", soundHint: 'like "ya" in "yard"', note: "Я begins with a y glide and ends with the a sound.", speechText: "я", strokeSteps: [...cyrillicStrokeSteps.ya] }
    ]
  };
})();
