(function registerKoreanData() {
  const koreanStrokeSteps = {
    giyeok: ["Draw the short top bar from left to right.", "Drop the right side straight down."],
    nieun: ["Draw the long left stroke from top to bottom.", "Sweep the base to the right."],
    digeut: ["Draw the top bar from left to right.", "Drop the left side straight down.", "Close the base to the right."],
    rieul: ["Draw the top bar from left to right.", "Step down on the right side.", "Sweep left across the middle.", "Finish with the bottom bar to the right."],
    mieum: ["Draw the top bar from left to right.", "Drop the left side straight down.", "Drop the right side straight down.", "Close the bottom bar from left to right."],
    bieup: ["Draw the top bar from left to right.", "Drop the left side straight down.", "Drop the right side straight down.", "Close the bottom bar from left to right.", "Add the middle bar across the center."],
    siot: ["Draw the left diagonal down toward the center.", "Draw the right diagonal down toward the center."],
    ieung: ["Trace a smooth circle in one continuous motion."],
    jieut: ["Draw the top bar from left to right.", "Draw the left diagonal down toward the center.", "Draw the right diagonal down toward the center."],
    chieut: ["Add the short top tick from left to right.", "Draw the main top bar below it.", "Draw the left diagonal down toward the center.", "Draw the right diagonal down toward the center."],
    kieuk: ["Draw the short top bar from left to right.", "Drop the right side straight down.", "Add the middle bar across the center."],
    tieut: ["Draw the top bar from left to right.", "Drop the left side straight down.", "Close the base to the right.", "Add the middle bar across the center."],
    pieup: ["Draw the top bar from left to right.", "Drop the left side straight down.", "Drop the right side straight down.", "Close the bottom bar from left to right.", "Add the upper middle bar.", "Add the lower middle bar."],
    hieut: ["Draw the short top bar from left to right.", "Add the middle bar across.", "Trace the circle below."],
    a: ["Draw the main vertical line from top to bottom.", "Add the short branch to the right."],
    ya: ["Draw the main vertical line from top to bottom.", "Add the upper right branch.", "Add the lower right branch."],
    eo: ["Draw the main vertical line from top to bottom.", "Add the short branch to the left."],
    yeo: ["Draw the main vertical line from top to bottom.", "Add the upper left branch.", "Add the lower left branch."],
    o: ["Draw the short vertical stem first.", "Draw the long horizontal line underneath it."],
    yo: ["Draw the left short stem above the line.", "Draw the right short stem above the line.", "Draw the long horizontal line beneath them."],
    u: ["Draw the long horizontal line first.", "Draw the short vertical stem below it."],
    yu: ["Draw the long horizontal line first.", "Add the left short stem below it.", "Add the right short stem below it."],
    eu: ["Draw the long horizontal line from left to right."],
    i: ["Draw the single vertical line from top to bottom."]
  };

  window.ScriptLearningData.SCRIPTS.korean = {
    id: "korean",
    name: "Korean",
    headline: "Korean Hangul Learning Studio",
    heroTitle: "See the jamo, hear the sound, trace the shape.",
    heroText:
      "Practice core Hangul consonants and vowels through the same speed match, quick choice, and tracing flow, with Korean browser playback when available.",
    countLabel: "24 basic jamo",
    sampleText: "ㄱ ㄴ ㄷ ㅏ ㅓ",
    unitSingular: "jamo",
    unitPlural: "jamo",
    glyphFont: '"Malgun Gothic", "Apple SD Gothic Neo", "Noto Sans KR", "Segoe UI", sans-serif',
    fontLoad: '160px "Malgun Gothic"',
    textDirection: "ltr",
    speechLang: "ko-KR",
    voiceHints: ["korean", "yuna", "yumi", "seoyeon", "heami", "sora"],
    speechRate: 0.82,
    matchDescription: "Match Hangul consonants and vowels to plain-English sound cues in fast rounds.",
    traceDescription: "Trace each jamo with clean stroke-order cues and play the Korean letter name.",
    traceBoardNote:
      "Hangul letters are built from clear lines and angles. Trace the rendered jamo and follow the ordered steps for stroke direction.",
    practiceNote:
      "The Hangul board focuses on the printed jamo shape. Replay the ordered steps to reinforce clean stroke order before writing full syllable blocks.",
    strokeCaption: "Replay walks the ordered Hangul stroke cues listed below.",
    strokeEmpty: "Replay will step through the ordered Hangul strokes listed below.",
    theme: {
      "bg-1": "#17214a",
      "bg-2": "#365ca8",
      accent: "#f06b5d",
      "accent-deep": "#b8433c",
      gold: "#ffd166",
      teal: "#3762b7"
    },
    strokeDemoFiles: {},
    letters: [
      { id: "giyeok", symbol: "ㄱ", name: "Giyeok", nativeName: "기역", soundLabel: "g / k", soundHint: "soft g before vowels, k at the end of a block", note: "Giyeok is the corner-shaped consonant used for g or k sounds.", speechText: "기역", strokeSteps: [...koreanStrokeSteps.giyeok] },
      { id: "nieun", symbol: "ㄴ", name: "Nieun", nativeName: "니은", soundLabel: "n", soundHint: 'like "n" in "no"', note: "Nieun is the clean L-shaped consonant for the n sound.", speechText: "니은", strokeSteps: [...koreanStrokeSteps.nieun] },
      { id: "digeut", symbol: "ㄷ", name: "Digeut", nativeName: "디귿", soundLabel: "d / t", soundHint: "often d at the start of a syllable and t at the end", note: "Digeut is the boxy consonant used for d or t sounds.", speechText: "디귿", strokeSteps: [...koreanStrokeSteps.digeut] },
      { id: "rieul", symbol: "ㄹ", name: "Rieul", nativeName: "리을", soundLabel: "r / l", soundHint: "between a light r and l depending on position", note: "Rieul shifts between r and l depending on where it sits in the syllable.", speechText: "리을", strokeSteps: [...koreanStrokeSteps.rieul] },
      { id: "mieum", symbol: "ㅁ", name: "Mieum", nativeName: "미음", soundLabel: "m", soundHint: 'like "m" in "moon"', note: "Mieum is the square-shaped m consonant.", speechText: "미음", strokeSteps: [...koreanStrokeSteps.mieum] },
      { id: "bieup", symbol: "ㅂ", name: "Bieup", nativeName: "비읍", soundLabel: "b / p", soundHint: "soft b at the start, p at the end of a block", note: "Bieup is the box consonant with a center bar for b or p sounds.", speechText: "비읍", strokeSteps: [...koreanStrokeSteps.bieup] },
      { id: "siot", symbol: "ㅅ", name: "Siot", nativeName: "시옷", soundLabel: "s", soundHint: 'like "s" in "see"', note: "Siot is the pointed consonant used for s sounds.", speechText: "시옷", strokeSteps: [...koreanStrokeSteps.siot] },
      { id: "ieung", symbol: "ㅇ", name: "Ieung", nativeName: "이응", soundLabel: "silent / ng", soundHint: "silent at the start of a syllable block, ng at the end", note: "Ieung is silent when it begins a block, but sounds like ng when it closes one.", speechText: "이응", strokeSteps: [...koreanStrokeSteps.ieung] },
      { id: "jieut", symbol: "ㅈ", name: "Jieut", nativeName: "지읒", soundLabel: "j", soundHint: 'like "j" in "jam"', note: "Jieut adds a top bar above the siot shape for the j sound.", speechText: "지읒", strokeSteps: [...koreanStrokeSteps.jieut] },
      { id: "chieut", symbol: "ㅊ", name: "Chieut", nativeName: "치읓", soundLabel: "ch", soundHint: 'like "ch" in "cheese"', note: "Chieut is jieut with an extra top stroke for a stronger ch sound.", speechText: "치읓", strokeSteps: [...koreanStrokeSteps.chieut] },
      { id: "kieuk", symbol: "ㅋ", name: "Kieuk", nativeName: "키읔", soundLabel: "k", soundHint: 'a crisp aspirated "k"', note: "Kieuk builds on giyeok by adding a crossbar for a stronger k sound.", speechText: "키읔", strokeSteps: [...koreanStrokeSteps.kieuk] },
      { id: "tieut", symbol: "ㅌ", name: "Tieut", nativeName: "티읕", soundLabel: "t", soundHint: 'a crisp aspirated "t"', note: "Tieut builds on digeut with an extra center bar for a stronger t sound.", speechText: "티읕", strokeSteps: [...koreanStrokeSteps.tieut] },
      { id: "pieup", symbol: "ㅍ", name: "Pieup", nativeName: "피읖", soundLabel: "p", soundHint: 'a crisp aspirated "p"', note: "Pieup is the expanded p consonant with two inner bars.", speechText: "피읖", strokeSteps: [...koreanStrokeSteps.pieup] },
      { id: "hieut", symbol: "ㅎ", name: "Hieut", nativeName: "히읗", soundLabel: "h", soundHint: 'like "h" in "hat"', note: "Hieut combines a top bar, a middle bar, and a circle for the h sound.", speechText: "히읗", strokeSteps: [...koreanStrokeSteps.hieut] },
      { id: "a", symbol: "ㅏ", name: "A", nativeName: "아", soundLabel: "a", soundHint: 'like "a" in "father"', note: "ㅏ is the basic vertical vowel with a branch on the right.", speechText: "아", strokeSteps: [...koreanStrokeSteps.a] },
      { id: "ya", symbol: "ㅑ", name: "Ya", nativeName: "야", soundLabel: "ya", soundHint: 'like "ya" in "yacht"', note: "ㅑ doubles the right-side branches to make the ya sound.", speechText: "야", strokeSteps: [...koreanStrokeSteps.ya] },
      { id: "eo", symbol: "ㅓ", name: "EO", nativeName: "어", soundLabel: "eo", soundHint: "a soft open o sound used in Korean words like 서울", note: "ㅓ is the mirrored partner of ㅏ with its branch on the left.", speechText: "어", strokeSteps: [...koreanStrokeSteps.eo] },
      { id: "yeo", symbol: "ㅕ", name: "Yeo", nativeName: "여", soundLabel: "yeo", soundHint: "the y version of eo", note: "ㅕ adds two left-side branches for the yeo sound.", speechText: "여", strokeSteps: [...koreanStrokeSteps.yeo] },
      { id: "o", symbol: "ㅗ", name: "O", nativeName: "오", soundLabel: "o", soundHint: 'like "o" in "go", but cleaner and shorter', note: "ㅗ is the horizontal vowel with a short stem above the line.", speechText: "오", strokeSteps: [...koreanStrokeSteps.o] },
      { id: "yo", symbol: "ㅛ", name: "Yo", nativeName: "요", soundLabel: "yo", soundHint: 'like "yo" in "yoga"', note: "ㅛ doubles the short upper stems to make the yo sound.", speechText: "요", strokeSteps: [...koreanStrokeSteps.yo] },
      { id: "u", symbol: "ㅜ", name: "U", nativeName: "우", soundLabel: "u / oo", soundHint: 'like "oo" in "food"', note: "ㅜ is the lower-stem partner of ㅗ for the u sound.", speechText: "우", strokeSteps: [...koreanStrokeSteps.u] },
      { id: "yu", symbol: "ㅠ", name: "Yu", nativeName: "유", soundLabel: "yu", soundHint: 'like "you"', note: "ㅠ doubles the short lower stems to make the yu sound.", speechText: "유", strokeSteps: [...koreanStrokeSteps.yu] },
      { id: "eu", symbol: "ㅡ", name: "EU", nativeName: "으", soundLabel: "eu", soundHint: "a flat Korean vowel made with relaxed lips", note: "ㅡ is the long horizontal vowel used for the eu sound.", speechText: "으", strokeSteps: [...koreanStrokeSteps.eu] },
      { id: "i", symbol: "ㅣ", name: "I", nativeName: "이", soundLabel: "i / ee", soundHint: 'like "ee" in "see"', note: "ㅣ is the simplest Hangul vowel: one clean vertical line.", speechText: "이", strokeSteps: [...koreanStrokeSteps.i] }
    ]
  };
})();
